openapi: 3.0.0

info:
  title: Inventory Management API
  version: 1.0.0
  description: API documentation for Inventory Management System

servers:
   url: "https://inventory-management-system1-ptf7.onrender.com",

paths:
  /api/auth/register:
    post:
      summary: Register User
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully

  /api/auth/login:
    post:
      summary: Login User
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Auth successful
        '401':
          description: Invalid credentials

  /api/products:
    get:
      summary: Get All Products
      tags:
        - Products
      responses:
        '200':
          description: List of products

    post:
      summary: Create Product
      tags:
        - Products
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                quantity:
                  type: integer
                image:
                  type: string
      responses:
        '201':
          description: Product created successfully

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT